### PR TITLE
Show ways to solve issues with busy port and privileges

### PR DESCRIPTION
**Pull request by xamgore**
screenshot

### CODE REVIEW

**Comment by ai** [comment]
Great work! Yeap, let’s combine PRs. I will accept #15 and then you will improve it. Deal?

**Comment by xamgore** [comment]
Ok! :smile:

**Comment by ai** [comment]
I will ping you after few days and mention in next tweet.

**Comment by ai** [comment]
Hi. I accept that PR, now you can make it better :). I like you way to think.

**Comment by ai** [comment]
Does new code is good for your ideas? We can refactor it as well.

**Comment by xamgore** [comment]
Hello, agian. Sorry for silence, I was busy a little bit :relieved:

As I can understand you want to see error explanations with code and links, yes?

**Comment by ai** [comment]
I am not sure about link (because I just have no good link yet).

But I like how you explained errors in screenshots in first comment. So, I want:

1. Split `EACCESS` error into file access (like loading certificate without file acccess) and port acces (using >1024 port without root access).
2. Improve current explanation text. Code to fix a problem is great idea.

**Comment by xamgore** [comment]
In case of file access error, we can give an instruction either to run server under the root, or to change the file permission (with chmod/chroot, for example). The first one works in any conditions, but is dangerous for production, the second needs information about the environment (to clearly explain the solution) and can be too complex to implement. Should we take two of options?

**Comment by ai** [comment]
Second one, for me opinion. Server running with root privileges is very bad b practice. We can write something like "as your DevOps what user should be used to access for this file".

**Comment by ai** [comment]
@xamgore don’t ignore people ;). If you have no time, tell me it ;).

**Comment by xamgore** [comment]
@ai sorry, but yes, I have serious health problems. I will update PR tonight, I _promise_.

**Comment by ai** [comment]
Don’t rush :). Just keep in touch. This issue is not time sensitive.

**Comment by ai** [comment]
Great. But does running on `root` is a good way to fix problem? I think it is very dangerous.

**Comment by xamgore** [comment]
I have read that an EACCESS error can be thrown on Windows, if a firewall or an antivirus (ie kaspersky) blocks all network stuff. That's actually crazy, can't even imagine how to test such issues. And as you understand, a firewall issue is not connected to a port one (we show hints only for ports).

> But does running on root is a good way to fix problem? I think it is very dangerous.

While you are developing things it doesn't matter. You just wanna the logux-server to work, so that you have time to solve more important problems. Anyway, it's easy to remove the hint, nobody will get hurt :)

**Comment by ai** [comment]
Good, I will pick up changes to master today or tomorrow.

**Comment by ai** [comment]
Do you have a Twitter? I need a name for announce :).

**Comment by xamgore** [comment]
Stop-stop, it's still not ready :smile: 

I want to take the laptop of my girlfriend to check the macos solution for `eaddrinuse`. And to write tests (and emulate the error with certificates file permission).

**Comment by ai** [comment]
Sure :D.

In this case, fix `master` by updating snapshots with `jest -u`.

**Comment by xamgore** [comment]
Yeah, I still remember about this pull request, don't worry :smile:

**Comment by ai** [comment]
Do you want to rebase PR? Your PR is really useful.

**Comment by xamgore** [comment]
May be this PR should wait for another 2 years? :smile: 

ok, working on it right now

**Comment by xamgore** [comment]
image

image

**Comment by ai** [comment]
Perfect :heart_eyes:

**Comment by ai** [comment]
Seems like you need to update snapshots in tests by `npx jest -u -i`

**Comment by xamgore** [comment]
I suppose you should call `jest -u` and push to the branch by your own. If it's fine for you, I can do it myself.

**Comment by ai** [comment]
Yeap, in current GitHub culture updating snapshots is on PR author (to be sure that PR is working)

**Comment by xamgore** [comment]
>  is on PR author (to be sure that PR is working)

If PR author makes a mistake, overrides jest snapshots, then CI won't show problems with the code as tests were passed. It sounds weird, isn't it?

**Comment by ai** [comment]
I am checking snapshot changes as well :)

**Comment by ai** [comment]
`flatMap` is not available in Node.js 10 (we need to support it at least for few years since it was LTS release)

**Pull request merged**
