### PR TITLE
Colorize actionId, nodeId and client ids

### PR DESCRIPTION
**Pull request by bijela-gora**
Link to the previous attempt to address the issue: https://github.com/logux/server/pull/127

### CODE REVIEW

**Comment by ai** [comment]
Looks good. I will try to merge it when I will be back home.

**Comment by bijela-gora** [comment]
I'm sure that part of task about Client ID was not done

> Добавить Client ID в human-formatter записях об action.

**Comment by bijela-gora** [comment]
Screenshot from 2022-04-19 12-19-15

```
        Action: 
          id:   "1650363005200 1:LJn2x2r0:5duYiO0l 1"
        Meta:   
          clients:     ["1:LJn2x2r0"]
          server:      "server:UcCgMiWc"
```

This fields should also be colorized?

**Comment by ai** [comment]
Yes. But keep `server:` prefix without color.

**Comment by bijela-gora** [comment]
Screenshot from 2022-04-19 15-29-14


I feel a strong internal resistance to what I am doing. I hope you have a clear understanding of what needs to be done.

**Comment by ai** [comment]
What do you worry about?

Use case:
1. You have a long list of operations (50+)
2. You need to quickly find a records about some action
3. You remember that it has blue-green-red ID. Now you can scan log just by looking on colors.

**Comment by bijela-gora** [comment]
Added the code to colorize client ids: https://github.com/logux/server/pull/128/files#diff-f6f47918804ef2911fa9330fa7f9d2b65f6b0fc61d49b4ab473f7af408d8698aR165

Added test for client ids: https://github.com/logux/server/pull/128/files#diff-997639ee9d9132d240f511dde5b22b433eff4b1846dde33b5ae122f0bf49afceR484

**Comment by bijela-gora** [comment]
@ai should something else be done in scope of this MR?

**Comment by ai** [comment]
Everything looks good. Sorry don't have a time to merge because I am preparing a talk.

**Pull request merged**
